#!/usr/bin/env python3
"""bpmn_json2promela.py — JSON → Promela model + SPIN verification.

Converts a BPMN JSON model into a Promela (.pml) specification,
then runs SPIN to verify:
  1. Deadlock freedom (invalid end states)
  2. Reachability: every endEvent is reachable
  3. Liveness: every process eventually terminates

Usage:
    python3 bpmn_json2promela.py input.json [--verify] [--max-milestones N]

--verify       Run SPIN verification after generating .pml
--max-milestones N  Bound the milestone loop to N iterations (default: 3)
"""

import json, sys, subprocess, os, tempfile
from pathlib import Path

GATEWAY_TYPES = {"exclusiveGateway", "eventBasedGateway"}
EVENT_TYPES = {"startEvent", "endEvent", "intermediateCatchEvent", "boundaryEvent"}
TASK_TYPES = {"userTask", "serviceTask", "manualTask"}


def load(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def build_graph(pool):
    """Build adjacency list and element lookup for a pool."""
    elements = {el["id"]: el for el in pool["elements"]}
    fwd = {eid: [] for eid in elements}  # eid -> [(target_eid, flow)]

    for f in pool.get("flows", []):
        fwd[f["from"]].append((f["to"], f))

    return elements, fwd


def find_start(elements):
    for eid, el in elements.items():
        if el["type"] == "startEvent":
            return eid
    return None


def find_ends(elements):
    return [eid for eid, el in elements.items() if el["type"] == "endEvent"]


def gen_promela(model, max_milestones=3):
    """Generate Promela source from BPMN JSON model.

    Handles:
    - Message flow channels (send/receive)
    - Exclusive gateways: loop vs decision (non-deterministic)
    - Event-based gateways: race between message catch and signal catch
    - Signal events: broadcast via global boolean flags
    - Boundary events: alternative transition from attached task
    - Failure propagation: signal end events set a flag checked by all processes
    """
    lines = []
    w = lines.append

    w(f"/* Promela model: {model['id']} */")
    w(f"/* Generated by bpmn_json2promela.py */")
    w(f"/* Max milestone iterations: {max_milestones} */")
    w("")
    w(f"#define MAX_MILESTONES {max_milestones}")
    w("")

    # Enumerate all element IDs as mtype
    all_ids = []
    for pool in model["pools"]:
        for el in pool["elements"]:
            all_ids.append(el["id"])
    all_ids.append("DONE")

    w(f"mtype = {{ {', '.join(all_ids)} }};")
    w("")

    # Channels for message flows
    msg_flows = model.get("messageFlows", [])
    if msg_flows:
        w("/* Message flow channels */")
        for mf in msg_flows:
            w(f"chan ch_{mf['id']} = [1] of {{ bit }};")
        w("")

    # --- Signal flags ---
    signals = model.get("signals", [])
    if signals:
        w("/* Signal broadcast flags */")
        for sig in signals:
            w(f"bool sig_{sig['id']} = false;")
        w("")

    # --- Failure detection ---
    # Signal-throwing end events create a process failure flag
    fail_end_to_proc = {}
    for pool in model["pools"]:
        for el in pool["elements"]:
            if el["type"] == "endEvent" and el.get("trigger") == "signal":
                fail_end_to_proc[el["id"]] = pool["processId"]
    fail_procs = sorted(set(fail_end_to_proc.values()))

    # State variables for each process (for LTL assertions)
    for pool in model["pools"]:
        pid = pool["processId"]
        w(f"mtype {pid}_state = {find_start(build_graph(pool)[0])};")
    w("")

    # Build message flow lookups
    send_after = {}   # element_id -> [channel_name]
    recv_before = {}  # element_id -> [channel_name]

    for mf in msg_flows:
        send_after.setdefault(mf["from"], []).append(f"ch_{mf['id']}")
        recv_before.setdefault(mf["to"], []).append(f"ch_{mf['id']}")

    # Generate each process
    for pool in model["pools"]:
        pid = pool["processId"]
        elements, fwd = build_graph(pool)
        start = find_start(elements)

        # Identify elements that are targets of event-based gateways
        # Their channel ops are handled by the gateway, not by the element itself
        ebg_targets = set()
        for eid, el in elements.items():
            if el["type"] == "eventBasedGateway":
                for tgt, _ in fwd.get(eid, []):
                    ebg_targets.add(tgt)

        # Identify boundary events attached to tasks
        boundary_of = {}  # host_task_id -> [(boundary_eid, boundary_el)]
        for eid, el in elements.items():
            if el.get("attachedToRef") and el["attachedToRef"] in elements:
                boundary_of.setdefault(el["attachedToRef"], []).append((eid, el))

        # All signal flags (for failure-aware blocking)
        all_sig_flags = [f"sig_{sig['id']}" for sig in signals]
        needs_end_label = False

        w(f"/* --- {pid} --- */")
        w(f"active proctype {pid}() {{")
        w(f"  byte milestone_i = 0;")
        w(f"")
        w(f"  do")

        for eid, el in elements.items():
            etype = el["type"]
            targets = fwd.get(eid, [])

            # Skip boundary events attached to tasks (handled inline)
            if el.get("attachedToRef"):
                # Boundary event: just a passthrough state
                w(f"  :: ({pid}_state == {eid}) ->")
                if len(targets) == 1:
                    tgt, _ = targets[0]
                    w(f"     {pid}_state = {tgt};")
                elif len(targets) == 0:
                    w(f"     {pid}_state = DONE;")
                    w(f"     break;")
                continue

            w(f"  :: ({pid}_state == {eid}) ->")

            # --- Blocking channel operations ---
            # Skip if this element is a target of an event-based gateway
            # (its channel ops are handled by the gateway)
            if eid not in ebg_targets:
                has_recv = eid in recv_before
                has_send = eid in send_after

                if (has_recv or has_send) and all_sig_flags:
                    fail_guard = " || ".join(all_sig_flags)
                    needs_end_label = True
                    for ch in recv_before.get(eid, []):
                        w(f"     if")
                        w(f"     :: {ch} ? 1 -> skip;  /* receive */")
                        w(f"     :: ({fail_guard}) -> goto end_{pid};")
                        w(f"     fi;")
                    for ch in send_after.get(eid, []):
                        w(f"     if")
                        w(f"     :: {ch} ! 1 -> skip;  /* send */")
                        w(f"     :: ({fail_guard}) -> goto end_{pid};")
                        w(f"     fi;")
                else:
                    for ch in recv_before.get(eid, []):
                        w(f"     {ch} ? 1;  /* receive message */")
                    for ch in send_after.get(eid, []):
                        w(f"     {ch} ! 1;  /* send message */")

            # Timer catch
            if etype == "intermediateCatchEvent" and el.get("trigger") == "timer":
                w(f"     skip;  /* timer wait */")

            # --- Transitions ---
            if etype == "endEvent":
                # Signal-throwing end events set signal + failure flags
                if el.get("trigger") == "signal" and el.get("signalRef"):
                    w(f"     sig_{el['signalRef']} = true;  /* throw signal */")
                w(f"     {pid}_state = DONE;")
                w(f"     break;")

            elif etype == "eventBasedGateway" and len(targets) >= 2:
                # Event-based gateway: race between catch events
                w(f"     if")
                for tgt, fl in targets:
                    tgt_el = elements.get(tgt)
                    if tgt_el and tgt_el.get("trigger") == "message":
                        channels = recv_before.get(tgt, [])
                        if channels:
                            w(f"     :: {channels[0]} ? 1 ->  /* message catch */")
                            w(f"        {pid}_state = {tgt};")
                        else:
                            w(f"     :: true ->  /* -> {tgt} */")
                            w(f"        {pid}_state = {tgt};")
                    elif tgt_el and tgt_el.get("trigger") == "signal":
                        sig_ref = tgt_el.get("signalRef", "")
                        w(f"     :: (sig_{sig_ref}) ->  /* signal catch */")
                        w(f"        {pid}_state = {tgt};")
                    else:
                        w(f"     :: true ->  /* -> {tgt} */")
                        w(f"        {pid}_state = {tgt};")
                w(f"     fi;")

            elif etype in GATEWAY_TYPES and len(targets) >= 2:
                gw_name = el.get("name", "") or ""
                is_loop_gw = "Последний" in gw_name or "последний" in gw_name
                if is_loop_gw:
                    w(f"     if")
                    for tgt, fl in targets:
                        cond_name = fl.get("name", "")
                        if "Нет" in cond_name:
                            w(f"     :: (milestone_i < MAX_MILESTONES) ->  /* loop back */")
                            w(f"        milestone_i++;")
                            w(f"        {pid}_state = {tgt};")
                        else:
                            w(f"     :: (milestone_i >= MAX_MILESTONES) ->  /* exit loop */")
                            w(f"        {pid}_state = {tgt};")
                    w(f"     fi;")
                else:
                    w(f"     if")
                    for tgt, fl in targets:
                        w(f"     :: true ->  /* -> {tgt} */")
                        w(f"        {pid}_state = {tgt};")
                    w(f"     fi;")

            elif len(targets) == 1:
                tgt, _ = targets[0]
                # Check for boundary events attached to this element
                if eid in boundary_of:
                    w(f"     if")
                    w(f"     :: true ->  /* normal */")
                    w(f"        {pid}_state = {tgt};")
                    for beid, bel in boundary_of[eid]:
                        if bel.get("trigger") == "signal" and bel.get("signalRef"):
                            w(f"     :: (sig_{bel['signalRef']}) ->  /* boundary signal */")
                            w(f"        {pid}_state = {beid};")
                    w(f"     fi;")
                else:
                    w(f"     {pid}_state = {tgt};")

            elif len(targets) == 0 and etype != "endEvent":
                w(f"     assert(false);  /* dead end! */")

        w(f"  od;")
        if needs_end_label:
            w(f"end_{pid}: skip;  /* SPIN: valid end state for failure path */")
        w(f"  {pid}_state = DONE;")
        w(f"}}")
        w("")

    # LTL properties
    w("/* LTL Properties */")
    for pool in model["pools"]:
        pid = pool["processId"]
        w(f"ltl terminates_{pid} {{ <>({pid}_state == DONE) }}")

    w("")
    w("/* Deadlock freedom is checked by SPIN's built-in invalid-end-state detection */")

    return "\n".join(lines) + "\n"


def run_spin(pml_path, work_dir=None):
    """Run SPIN verification and return results."""
    if work_dir is None:
        work_dir = pml_path.parent

    results = []
    pml_abs = str(pml_path.resolve())

    # 1. Check for deadlocks (invalid end states)
    print("\n─── SPIN: Deadlock (invalid end states) ───")
    r = subprocess.run(
        ["spin", "-run", "-noclaim", "-m10000", pml_abs],
        capture_output=True, cwd=work_dir, timeout=30
    )
    output = (r.stdout + r.stderr).decode("utf-8", errors="replace")
    if "errors: 0" in output:
        results.append(("PASS", "Deadlock freedom (no invalid end states)"))
        print("  ✓ PASS — нет deadlock'ов")
    else:
        results.append(("FAIL", "Deadlock detected"))
        print("  ✗ FAIL — обнаружен deadlock")
        print(output[-500:])

    # 2. Check LTL properties (reachability/liveness)
    # First, extract LTL names from the .pml file
    ltl_names = []
    for line in Path(pml_abs).read_text().split("\n"):
        if line.startswith("ltl "):
            name = line.split("{")[0].replace("ltl ", "").strip()
            ltl_names.append(name)

    for ltl in ltl_names:
        print(f"\n─── SPIN: LTL {ltl} ───")
        r = subprocess.run(
            ["spin", "-run", f"-ltl", ltl, "-m10000", pml_abs],
            capture_output=True, cwd=work_dir, timeout=30
        )
        output = (r.stdout + r.stderr).decode("utf-8", errors="replace")
        if "errors: 0" in output:
            results.append(("PASS", f"LTL {ltl}"))
            print(f"  ✓ PASS — {ltl}")
        else:
            results.append(("FAIL", f"LTL {ltl}"))
            print(f"  ✗ FAIL — {ltl}")
            # Show last part of output for diagnosis
            for line in output.split("\n"):
                if "error" in line.lower() or "violation" in line.lower():
                    print(f"    {line}")

    # Cleanup SPIN artifacts
    for f in Path(work_dir).glob("pan*"):
        f.unlink(missing_ok=True)
    for f in ["_spin_nvr.tmp"]:
        (Path(work_dir) / f).unlink(missing_ok=True)

    return results


def main():
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        print(__doc__)
        sys.exit(0)

    src = Path(args[0])
    do_verify = "--verify" in args
    max_m = 3
    if "--max-milestones" in args:
        idx = args.index("--max-milestones")
        max_m = int(args[idx + 1])

    model = load(src)
    pml = gen_promela(model, max_milestones=max_m)
    dst = src.with_suffix(".pml")
    dst.write_text(pml, encoding="utf-8")
    print(f"✓ Promela модель: {dst}  ({len(pml)} bytes)")

    if do_verify:
        print(f"\n═══ SPIN Verification: {dst.name} ═══")
        results = run_spin(dst)
        print(f"\n═══ Итого ═══")
        fails = 0
        for status, msg in results:
            icon = "✓" if status == "PASS" else "✗"
            print(f"  {icon} {msg}")
            if status == "FAIL":
                fails += 1
        if fails:
            print(f"\n✗ {fails} проверок провалено")
            sys.exit(1)
        else:
            print(f"\n✓ Все {len(results)} проверок пройдены")


if __name__ == "__main__":
    main()
