#!/usr/bin/env python3
"""bpmn_json2uppaal.py — JSON → UPPAAL timed automata (.xml) + verification.

Converts a BPMN JSON model into an UPPAAL timed automata network.
Adds real-time constraints for timer events (unique to UPPAAL vs SPIN/NuSMV).

Usage:
    python3 bpmn_json2uppaal.py input.json [--verify] [--max-milestones N]

--verify       Run verifyta after generating .xml
--max-milestones N  Bound milestone loop to N (default: 3)
"""

import json, sys, subprocess
from pathlib import Path
from xml.sax.saxutils import escape as esc

GATEWAY_TYPES = {"exclusiveGateway", "eventBasedGateway"}


def load(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def build_graph(pool):
    elements = {el["id"]: el for el in pool["elements"]}
    fwd = {eid: [] for eid in elements}
    for f in pool.get("flows", []):
        fwd[f["from"]].append((f["to"], f))
    return elements, fwd


def find_start(elements):
    for eid, el in elements.items():
        if el["type"] == "startEvent":
            return eid
    return None


def gen_uppaal(model, max_m=3):
    lines = []
    w = lines.append

    signals = model.get("signals", [])
    msg_flows = model.get("messageFlows", [])
    pools = model["pools"]
    proc_ids = [p["processId"] for p in pools]

    send_after = {}
    recv_before = {}
    for mf in msg_flows:
        send_after.setdefault(mf["from"], []).append(mf["id"])
        recv_before.setdefault(mf["to"], []).append(mf["id"])

    proc_of = {}
    for pool in pools:
        for el in pool["elements"]:
            proc_of[el["id"]] = pool["processId"]

    # ── XML header ──
    w('<?xml version="1.0" encoding="utf-8"?>')
    w('<!DOCTYPE nta PUBLIC \'-//Uppaal Team//DTD Flat System 1.6//EN\'')
    w('  \'http://www.it.uu.se/research/group/darts/uppaal/flat-1_6.dtd\'>')
    w('<nta>')

    # ── Global declarations ──
    w('<declaration>')
    w(f'// BPMN model: {model["id"]}')
    w(f'// Generated by bpmn_json2uppaal.py')
    w(f'const int MAX_M = {max_m};')
    w('')
    w('// Message flow channels (binary synchronization)')
    for mf in msg_flows:
        w(f'chan {mf["id"]};  // {mf.get("name", "")}')
    w('')
    w('// Signal broadcast channels')
    for sig in signals:
        w(f'broadcast chan sig_{sig["id"]};')
    w('')
    w('// Signal state flags (for guard conditions)')
    for sig in signals:
        w(f'bool sig_{sig["id"]}_fired = false;')
    w('</declaration>')
    w('')

    # ── Process templates ──
    for pool in pools:
        pid = pool["processId"]
        elements, fwd = build_graph(pool)
        start = find_start(elements)

        ebg_targets = set()
        for eid, el in elements.items():
            if el["type"] == "eventBasedGateway":
                for tgt, _ in fwd.get(eid, []):
                    ebg_targets.add(tgt)

        boundary_of = {}
        for eid, el in elements.items():
            if el.get("attachedToRef") and el["attachedToRef"] in elements:
                boundary_of.setdefault(el["attachedToRef"], []).append((eid, el))

        all_sig_flags = [f"sig_{sig['id']}_fired" for sig in signals]

        w(f'<template>')
        w(f'<name>{pid}</name>')
        w(f'<declaration>')
        w(f'int milestone = 0;')
        # Add clock for timer events
        has_timer = any(el.get("trigger") == "timer" for el in pool["elements"])
        if has_timer:
            w(f'clock timer;')
        w(f'</declaration>')

        # ── Locations ──
        el_list = list(elements.items())
        for i, (eid, el) in enumerate(el_list):
            x = (i % 8) * 180
            y = (i // 8) * 160
            w(f'<location id="{eid}" x="{x}" y="{y}">')
            w(f'<name x="{x-10}" y="{y-30}">{eid}</name>')
            w(f'</location>')

        # DONE location
        x = (len(el_list) % 8) * 180
        y = (len(el_list) // 8) * 160
        w(f'<location id="DONE_{pid}" x="{x}" y="{y}">')
        w(f'<name x="{x-10}" y="{y-30}">DONE</name>')
        w(f'</location>')

        w(f'<init ref="{start}"/>')

        # ── Transitions ──
        for eid, el in elements.items():
            etype = el["type"]
            targets = fwd.get(eid, [])

            if el.get("attachedToRef"):
                # Boundary event passthrough
                if targets:
                    tgt, _ = targets[0]
                    w(f'<transition>')
                    w(f'<source ref="{eid}"/>')
                    w(f'<target ref="{tgt}"/>')
                    w(f'</transition>')
                else:
                    w(f'<transition>')
                    w(f'<source ref="{eid}"/>')
                    w(f'<target ref="DONE_{pid}"/>')
                    w(f'</transition>')
                continue

            if etype == "endEvent":
                sync = ""
                assign = ""
                if el.get("trigger") == "signal" and el.get("signalRef"):
                    sr = el["signalRef"]
                    sync = f'<label kind="synchronisation">sig_{sr}!</label>'
                    assign = f'<label kind="assignment">sig_{sr}_fired = true</label>'
                w(f'<transition>')
                w(f'<source ref="{eid}"/>')
                w(f'<target ref="DONE_{pid}"/>')
                if sync:
                    w(sync)
                if assign:
                    w(assign)
                w(f'</transition>')

            elif etype == "eventBasedGateway" and len(targets) >= 2:
                for tgt, _ in targets:
                    tgt_el = elements.get(tgt)
                    if tgt_el and tgt_el.get("trigger") == "message":
                        chs = recv_before.get(tgt, [])
                        if chs:
                            w(f'<transition>')
                            w(f'<source ref="{eid}"/>')
                            w(f'<target ref="{tgt}"/>')
                            w(f'<label kind="synchronisation">{chs[0]}?</label>')
                            w(f'</transition>')
                        else:
                            w(f'<transition>')
                            w(f'<source ref="{eid}"/>')
                            w(f'<target ref="{tgt}"/>')
                            w(f'</transition>')
                    elif tgt_el and tgt_el.get("trigger") == "signal":
                        sr = tgt_el.get("signalRef", "")
                        w(f'<transition>')
                        w(f'<source ref="{eid}"/>')
                        w(f'<target ref="{tgt}"/>')
                        w(f'<label kind="synchronisation">sig_{sr}?</label>')
                        w(f'</transition>')
                    else:
                        w(f'<transition>')
                        w(f'<source ref="{eid}"/>')
                        w(f'<target ref="{tgt}"/>')
                        w(f'</transition>')

            elif etype in GATEWAY_TYPES and len(targets) >= 2:
                gw_name = el.get("name", "") or ""
                is_loop = "Последний" in gw_name or "последний" in gw_name
                if is_loop:
                    for tgt, fl in targets:
                        cn = fl.get("name", "")
                        if "Нет" in cn:
                            w(f'<transition>')
                            w(f'<source ref="{eid}"/>')
                            w(f'<target ref="{tgt}"/>')
                            w(f'<label kind="guard">milestone &lt; MAX_M</label>')
                            w(f'<label kind="assignment">milestone++</label>')
                            w(f'</transition>')
                        else:
                            w(f'<transition>')
                            w(f'<source ref="{eid}"/>')
                            w(f'<target ref="{tgt}"/>')
                            w(f'<label kind="guard">milestone &gt;= MAX_M</label>')
                            w(f'</transition>')
                else:
                    for tgt, _ in targets:
                        w(f'<transition>')
                        w(f'<source ref="{eid}"/>')
                        w(f'<target ref="{tgt}"/>')
                        w(f'</transition>')

            elif len(targets) == 1:
                tgt, _ = targets[0]
                has_recv = eid in recv_before and eid not in ebg_targets
                has_send = eid in send_after

                if eid in boundary_of:
                    # Normal path
                    w(f'<transition>')
                    w(f'<source ref="{eid}"/>')
                    w(f'<target ref="{tgt}"/>')
                    w(f'</transition>')
                    # Boundary signal paths
                    for beid, bel in boundary_of[eid]:
                        if bel.get("signalRef"):
                            w(f'<transition>')
                            w(f'<source ref="{eid}"/>')
                            w(f'<target ref="{beid}"/>')
                            w(f'<label kind="synchronisation">sig_{bel["signalRef"]}?</label>')
                            w(f'</transition>')
                elif has_recv and has_send:
                    # Both receive then send — model as two transitions via intermediate
                    # Simplified: single transition with sync on first channel
                    chs_r = recv_before.get(eid, [])
                    chs_s = send_after.get(eid, [])
                    w(f'<transition>')
                    w(f'<source ref="{eid}"/>')
                    w(f'<target ref="{tgt}"/>')
                    if chs_r:
                        w(f'<label kind="synchronisation">{chs_r[0]}?</label>')
                    w(f'</transition>')
                    # Failure escape
                    if all_sig_flags:
                        for sf in all_sig_flags:
                            w(f'<transition>')
                            w(f'<source ref="{eid}"/>')
                            w(f'<target ref="DONE_{pid}"/>')
                            w(f'<label kind="guard">{sf}</label>')
                            w(f'</transition>')
                elif has_recv:
                    chs = recv_before.get(eid, [])
                    for ch in chs:
                        w(f'<transition>')
                        w(f'<source ref="{eid}"/>')
                        w(f'<target ref="{tgt}"/>')
                        w(f'<label kind="synchronisation">{ch}?</label>')
                        w(f'</transition>')
                    if all_sig_flags:
                        for sf in all_sig_flags:
                            w(f'<transition>')
                            w(f'<source ref="{eid}"/>')
                            w(f'<target ref="DONE_{pid}"/>')
                            w(f'<label kind="guard">{sf}</label>')
                            w(f'</transition>')
                elif has_send:
                    chs = send_after.get(eid, [])
                    for ch in chs:
                        w(f'<transition>')
                        w(f'<source ref="{eid}"/>')
                        w(f'<target ref="{tgt}"/>')
                        w(f'<label kind="synchronisation">{ch}!</label>')
                        w(f'</transition>')
                    if all_sig_flags:
                        for sf in all_sig_flags:
                            w(f'<transition>')
                            w(f'<source ref="{eid}"/>')
                            w(f'<target ref="DONE_{pid}"/>')
                            w(f'<label kind="guard">{sf}</label>')
                            w(f'</transition>')
                elif etype == "intermediateCatchEvent" and el.get("trigger") == "timer":
                    w(f'<transition>')
                    w(f'<source ref="{eid}"/>')
                    w(f'<target ref="{tgt}"/>')
                    w(f'<label kind="guard">timer &gt;= 30</label>')
                    w(f'<label kind="assignment">timer = 0</label>')
                    w(f'</transition>')
                else:
                    w(f'<transition>')
                    w(f'<source ref="{eid}"/>')
                    w(f'<target ref="{tgt}"/>')
                    w(f'</transition>')

            elif len(targets) == 0 and etype != "endEvent":
                w(f'<transition>')
                w(f'<source ref="{eid}"/>')
                w(f'<target ref="DONE_{pid}"/>')
                w(f'</transition>')

        w(f'</template>')
        w('')

    # ── System declaration ──
    w('<system>')
    for pid in proc_ids:
        w(f'{pid.lower()} = {pid}();')
    w(f'system {", ".join(p.lower() for p in proc_ids)};')
    w('</system>')
    w('')

    # ── Queries ──
    w('<queries>')

    # Deadlock freedom
    w('<query>')
    w(f'<formula>A[] not deadlock</formula>')
    w(f'<comment>Deadlock freedom (TCTL, unique to UPPAAL)</comment>')
    w('</query>')

    # Liveness for each process
    for pid in proc_ids:
        w(f'<query>')
        w(f'<formula>{pid.lower()}.DONE --&gt;</formula>')
        w(f'<comment>Reachability: {pid} can terminate</comment>')
        w(f'</query>')

    for pid in proc_ids:
        w(f'<query>')
        w(f'<formula>A&lt;&gt; {pid.lower()}.DONE</formula>')
        w(f'<comment>Liveness (TCTL): {pid} always eventually terminates</comment>')
        w(f'</query>')

    # Timer-specific property (unique to UPPAAL)
    w('<query>')
    w(f'<formula>A[] (process_sc.scTimer imply process_sc.timer &lt;= 60)</formula>')
    w(f'<comment>Timing: fundraising timer never exceeds 60 days (UPPAAL-specific)</comment>')
    w('</query>')

    w('</queries>')
    w('</nta>')

    return "\n".join(lines) + "\n"


def run_verifyta(xml_path):
    """Run UPPAAL verifyta command-line verifier."""
    print(f"\n═══ UPPAAL Verification: {xml_path.name} ═══")
    try:
        r = subprocess.run(
            ["verifyta", str(xml_path)],
            capture_output=True, timeout=120
        )
    except FileNotFoundError:
        print("  ✗ verifyta (UPPAAL CLI) не установлен.")
        print("  Скачайте: https://uppaal.org/downloads/")
        print(f"  Затем: verifyta {xml_path}")
        return []

    out = (r.stdout + r.stderr).decode("utf-8", errors="replace")
    results = []
    for line in out.split("\n"):
        if "Property" in line or "satisfied" in line or "NOT satisfied" in line:
            status = "PASS" if "satisfied" in line and "NOT" not in line else "FAIL"
            results.append((status, line.strip()))
            icon = "✓" if status == "PASS" else "✗"
            print(f"  {icon} {line.strip()}")

    if not results:
        print("  (не удалось разобрать результат)")
        print(out[-500:])

    return results


def main():
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        print(__doc__)
        sys.exit(0)

    src = Path(args[0])
    do_verify = "--verify" in args
    max_m = 3
    if "--max-milestones" in args:
        idx = args.index("--max-milestones")
        max_m = int(args[idx + 1])

    model = load(src)
    xml = gen_uppaal(model, max_m=max_m)
    dst = src.with_suffix(".uppaal.xml")
    dst.write_text(xml, encoding="utf-8")
    print(f"✓ UPPAAL модель: {dst}  ({len(xml)} bytes)")

    if do_verify:
        results = run_verifyta(dst)
        if results:
            fails = sum(1 for s, _ in results if s == "FAIL")
            print(f"\n═══ Итого: {len(results)} проверок, {fails} провалов ═══")


if __name__ == "__main__":
    main()
