#!/usr/bin/env python3
"""bpmn_json2smv.py — JSON → NuSMV model (.smv) + verification.

Converts a BPMN JSON model into a NuSMV specification for CTL/LTL verification.
Uses nondeterministic scheduler for asynchronous interleaving of BPMN pools.

Usage:
    python3 bpmn_json2smv.py input.json [--verify] [--max-milestones N]

--verify       Run NuSMV verification after generating .smv
--max-milestones N  Bound milestone loop to N iterations (default: 3)
"""

import json, sys, subprocess
from pathlib import Path

GATEWAY_TYPES = {"exclusiveGateway", "eventBasedGateway"}


def load(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def build_graph(pool):
    elements = {el["id"]: el for el in pool["elements"]}
    fwd = {eid: [] for eid in elements}
    for f in pool.get("flows", []):
        fwd[f["from"]].append((f["to"], f))
    return elements, fwd


def find_start(elements):
    for eid, el in elements.items():
        if el["type"] == "startEvent":
            return eid
    return None


def gen_smv(model, max_m=3):
    lines = []
    w = lines.append

    signals = model.get("signals", [])
    msg_flows = model.get("messageFlows", [])
    pools = model["pools"]
    proc_ids = [p["processId"] for p in pools]
    # Turn labels must differ from state variable names to avoid NuSMV conflicts
    turn_ids = [f"t_{pid}" for pid in proc_ids]

    send_after = {}
    recv_before = {}
    for mf in msg_flows:
        send_after.setdefault(mf["from"], []).append(mf["id"])
        recv_before.setdefault(mf["to"], []).append(mf["id"])

    w(f"-- NuSMV model: {model['id']}")
    w(f"-- Generated by bpmn_json2smv.py")
    w(f"-- Asynchronous interleaving via nondeterministic scheduler")
    w(f"-- Max milestone iterations: {max_m}")
    w("")
    w("MODULE main")
    w("")
    w("VAR")
    w(f"  turn : {{{', '.join(turn_ids)}}};")
    w("")

    for pool in pools:
        pid = pool["processId"]
        el_ids = [el["id"] for el in pool["elements"]] + ["DONE"]
        w(f"  {pid} : {{{', '.join(el_ids)}}};")
        w(f"  {pid}_m : 0..{max_m};")
    w("")

    for mf in msg_flows:
        w(f"  {mf['id']} : boolean;  -- channel: {mf.get('name','')}")
    w("")

    for sig in signals:
        w(f"  sig_{sig['id']} : boolean;  -- signal broadcast")
    w("")

    # ── ASSIGN ──
    w("ASSIGN")
    w("")
    w(f"  init(turn) := {{{', '.join(turn_ids)}}};")
    w(f"  next(turn) := {{{', '.join(turn_ids)}}};")
    w("")

    for pool in pools:
        pid = pool["processId"]
        elements, fwd = build_graph(pool)
        start = find_start(elements)
        w(f"  init({pid}) := {start};")
        w(f"  init({pid}_m) := 0;")

    for mf in msg_flows:
        w(f"  init({mf['id']}) := FALSE;")
    for sig in signals:
        w(f"  init(sig_{sig['id']}) := FALSE;")
    w("")

    # ── Process transitions ──
    all_sig_flags = [f"sig_{sig['id']}" for sig in signals]
    fail_guard = " | ".join(all_sig_flags) if all_sig_flags else "FALSE"

    for pool in pools:
        pid = pool["processId"]
        elements, fwd = build_graph(pool)

        ebg_targets = set()
        for eid, el in elements.items():
            if el["type"] == "eventBasedGateway":
                for tgt, _ in fwd.get(eid, []):
                    ebg_targets.add(tgt)

        boundary_of = {}
        for eid, el in elements.items():
            if el.get("attachedToRef") and el["attachedToRef"] in elements:
                boundary_of.setdefault(el["attachedToRef"], []).append((eid, el))

        w(f"  -- {pid}")
        w(f"  next({pid}) := case")

        for eid, el in elements.items():
            etype = el["type"]
            targets = fwd.get(eid, [])
            pre = f"turn = t_{pid} & {pid} = {eid}"

            if el.get("attachedToRef"):
                if targets:
                    tgt, _ = targets[0]
                    w(f"    {pre} : {tgt};")
                else:
                    w(f"    {pre} : DONE;")
                continue

            if etype == "endEvent":
                w(f"    {pre} : DONE;")

            elif etype == "eventBasedGateway" and len(targets) >= 2:
                for tgt, _ in targets:
                    tgt_el = elements.get(tgt)
                    if tgt_el and tgt_el.get("trigger") == "message":
                        chs = recv_before.get(tgt, [])
                        if chs:
                            w(f"    {pre} & {chs[0]} : {tgt};")
                        else:
                            w(f"    {pre} : {tgt};")
                    elif tgt_el and tgt_el.get("trigger") == "signal":
                        sr = tgt_el.get("signalRef", "")
                        w(f"    {pre} & sig_{sr} : {tgt};")
                    else:
                        w(f"    {pre} : {tgt};")

            elif etype in GATEWAY_TYPES and len(targets) >= 2:
                gw_name = el.get("name", "") or ""
                is_loop = "Последний" in gw_name or "последний" in gw_name
                if is_loop:
                    for tgt, fl in targets:
                        cn = fl.get("name", "")
                        if "Нет" in cn:
                            w(f"    {pre} & {pid}_m < {max_m} : {tgt};")
                        else:
                            w(f"    {pre} & {pid}_m >= {max_m} : {tgt};")
                else:
                    tgts = ", ".join(t for t, _ in targets)
                    w(f"    {pre} : {{{tgts}}};")

            elif len(targets) == 1:
                tgt, _ = targets[0]
                has_recv = eid in recv_before and eid not in ebg_targets
                has_send = eid in send_after

                if eid in boundary_of:
                    btgts = [tgt] + [be for be, _ in boundary_of[eid]]
                    for beid, bel in boundary_of[eid]:
                        if bel.get("signalRef"):
                            w(f"    {pre} & sig_{bel['signalRef']} : {{{', '.join(btgts)}}};")
                    w(f"    {pre} & !({fail_guard}) : {tgt};")
                elif has_recv:
                    chs = recv_before.get(eid, [])
                    cg = " & ".join(chs)
                    w(f"    {pre} & {cg} : {tgt};")
                    if all_sig_flags:
                        w(f"    {pre} & ({fail_guard}) : DONE;")
                elif has_send:
                    chs = send_after.get(eid, [])
                    cg = " & ".join(f"!{c}" for c in chs)
                    w(f"    {pre} & {cg} : {tgt};")
                    if all_sig_flags:
                        w(f"    {pre} & ({fail_guard}) : DONE;")
                else:
                    w(f"    {pre} : {tgt};")

            elif len(targets) == 0 and etype != "endEvent":
                w(f"    {pre} : DONE;  -- dead end")

        w(f"    TRUE : {pid};")
        w(f"  esac;")
        w("")

    # ── Milestone counters ──
    for pool in pools:
        pid = pool["processId"]
        elements, fwd = build_graph(pool)
        w(f"  next({pid}_m) := case")
        for eid, el in elements.items():
            if el["type"] == "exclusiveGateway" and "Последний" in (el.get("name", "") or ""):
                for tgt, fl in fwd.get(eid, []):
                    if "Нет" in (fl.get("name", "") or ""):
                        w(f"    turn = t_{pid} & {pid} = {eid} & {pid}_m < {max_m} : {pid}_m + 1;")
        w(f"    TRUE : {pid}_m;")
        w(f"  esac;")
        w("")

    # ── Channel transitions ──
    proc_of = {}
    for pool in pools:
        for el in pool["elements"]:
            proc_of[el["id"]] = pool["processId"]

    for mf in msg_flows:
        ch = mf["id"]
        sp = proc_of.get(mf["from"])
        rp = proc_of.get(mf["to"])
        w(f"  next({ch}) := case")
        if sp:
            w(f"    turn = t_{sp} & {sp} = {mf['from']} & !{ch} : TRUE;   -- send")
        if rp:
            w(f"    turn = t_{rp} & {rp} = {mf['to']} & {ch} : FALSE;  -- recv")
        w(f"    TRUE : {ch};")
        w(f"  esac;")
        w("")

    # ── Signal transitions ──
    for sig in signals:
        sf = f"sig_{sig['id']}"
        w(f"  next({sf}) := case")
        for pool in pools:
            pid = pool["processId"]
            for el in pool["elements"]:
                if el["type"] == "endEvent" and el.get("trigger") == "signal" \
                        and el.get("signalRef") == sig["id"]:
                    w(f"    turn = t_{pid} & {pid} = {el['id']} : TRUE;")
        w(f"    TRUE : {sf};")
        w(f"  esac;")
        w("")

    # ── Fairness constraints ──
    # Without fairness, scheduler can starve processes (give turns only to one)
    w("-- Fairness: each process gets scheduled infinitely often (no starvation)")
    for pool in pools:
        pid = pool["processId"]
        w(f"FAIRNESS turn = t_{pid}")
    w("")

    # ── CTL Properties ──
    w("-- ═══ CTL Properties (unique to NuSMV — SPIN cannot verify CTL) ═══")
    w("")
    for pool in pools:
        pid = pool["processId"]
        w(f"SPEC AF ({pid} = DONE)                                    -- liveness")
    w("")
    for pool in pools:
        pid = pool["processId"]
        w(f"SPEC AG (!({pid} = DONE) -> AF ({pid} = DONE))            -- soundness")
    w("")
    w("SPEC AG (EX TRUE)                                              -- deadlock freedom")
    w("")

    # ── LTL Properties (same as SPIN) ──
    w("-- ═══ LTL Properties (cross-check with SPIN) ═══")
    w("")
    for pool in pools:
        pid = pool["processId"]
        w(f"LTLSPEC F ({pid} = DONE)")
    w("")

    return "\n".join(lines) + "\n"


def run_nusmv(smv_path):
    """Run NuSMV verification."""
    print(f"\n═══ NuSMV Verification: {smv_path.name} ═══")
    try:
        r = subprocess.run(
            ["NuSMV", str(smv_path)],
            capture_output=True, timeout=60
        )
    except FileNotFoundError:
        try:
            r = subprocess.run(
                ["nuXmv", str(smv_path)],
                capture_output=True, timeout=60
            )
        except FileNotFoundError:
            print("  ✗ NuSMV / nuXmv не установлены.")
            print("  Скачайте: https://nusmv.fbk.eu/ или https://nuxmv.fbk.eu/")
            print(f"  Затем: NuSMV {smv_path}")
            return []

    out = (r.stdout + r.stderr).decode("utf-8", errors="replace")
    results = []
    for line in out.split("\n"):
        if "-- specification" in line or "-- LTL specification" in line:
            if "is true" in line:
                results.append(("PASS", line.strip()))
                print(f"  ✓ {line.strip()}")
            elif "is false" in line:
                results.append(("FAIL", line.strip()))
                print(f"  ✗ {line.strip()}")

    if not results:
        print("  (не удалось разобрать результат)")
        print(out[-1000:])

    return results


def main():
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        print(__doc__)
        sys.exit(0)

    src = Path(args[0])
    do_verify = "--verify" in args
    max_m = 3
    if "--max-milestones" in args:
        idx = args.index("--max-milestones")
        max_m = int(args[idx + 1])

    model = load(src)
    smv = gen_smv(model, max_m=max_m)
    dst = src.with_suffix(".smv")
    dst.write_text(smv, encoding="utf-8")
    print(f"✓ NuSMV модель: {dst}  ({len(smv)} bytes)")

    if do_verify:
        results = run_nusmv(dst)
        if results:
            fails = sum(1 for s, _ in results if s == "FAIL")
            print(f"\n═══ Итого: {len(results)} проверок, {fails} провалов ═══")


if __name__ == "__main__":
    main()
