/* Promela model: TO_BE_L1 */
/* Generated by bpmn_json2promela.py */
/* Max milestone iterations: 3 */

#define MAX_MILESTONES 3

mtype = { aStart, aPrepare, aSubmit, aMilestoneCycle, aEndOk, pStart, pModerate, pPublish, pDeploy, pEnd, scStart, scMint, scTimer, scGoal, scVoting, scApproved, scUnlock, scLast, scEndOk, scRefund, scEndFail, iStart, iKYC, iInvest, iVote, iEnd, DONE };

/* Message flow channels */
chan ch_MF_submit = [1] of { bit };
chan ch_MF_deploy = [1] of { bit };
chan ch_MF_invest = [1] of { bit };
chan ch_MF_vote = [1] of { bit };
chan ch_MF_bi = [1] of { bit };

mtype Process_Author_state = aStart;
mtype Process_Platform_state = pStart;
mtype Process_SmartContract_state = scStart;
mtype Process_Investor_state = iStart;

/* --- Process_Author --- */
active proctype Process_Author() {
  byte milestone_i = 0;

  do
  :: (Process_Author_state == aStart) ->
     Process_Author_state = aPrepare;
  :: (Process_Author_state == aPrepare) ->
     Process_Author_state = aSubmit;
  :: (Process_Author_state == aSubmit) ->
     ch_MF_submit ! 1;  /* send message */
     Process_Author_state = aMilestoneCycle;
  :: (Process_Author_state == aMilestoneCycle) ->
     ch_MF_bi ? 1;  /* receive message */
     Process_Author_state = aEndOk;
  :: (Process_Author_state == aEndOk) ->
     Process_Author_state = DONE;
     break;
  od;
  Process_Author_state = DONE;
}

/* --- Process_Platform --- */
active proctype Process_Platform() {
  byte milestone_i = 0;

  do
  :: (Process_Platform_state == pStart) ->
     ch_MF_submit ? 1;  /* receive message */
     Process_Platform_state = pModerate;
  :: (Process_Platform_state == pModerate) ->
     Process_Platform_state = pPublish;
  :: (Process_Platform_state == pPublish) ->
     Process_Platform_state = pDeploy;
  :: (Process_Platform_state == pDeploy) ->
     ch_MF_deploy ! 1;  /* send message */
     Process_Platform_state = pEnd;
  :: (Process_Platform_state == pEnd) ->
     Process_Platform_state = DONE;
     break;
  od;
  Process_Platform_state = DONE;
}

/* --- Process_SmartContract --- */
active proctype Process_SmartContract() {
  byte milestone_i = 0;

  do
  :: (Process_SmartContract_state == scStart) ->
     ch_MF_deploy ? 1;  /* receive message */
     Process_SmartContract_state = scMint;
  :: (Process_SmartContract_state == scMint) ->
     ch_MF_invest ? 1;  /* receive message */
     Process_SmartContract_state = scTimer;
  :: (Process_SmartContract_state == scTimer) ->
     skip;  /* timer wait */
     Process_SmartContract_state = scGoal;
  :: (Process_SmartContract_state == scGoal) ->
     if
     :: true ->  /* -> scVoting */
        Process_SmartContract_state = scVoting;
     :: true ->  /* -> scRefund */
        Process_SmartContract_state = scRefund;
     fi;
  :: (Process_SmartContract_state == scVoting) ->
     ch_MF_vote ? 1;  /* receive message */
     Process_SmartContract_state = scApproved;
  :: (Process_SmartContract_state == scApproved) ->
     if
     :: true ->  /* -> scUnlock */
        Process_SmartContract_state = scUnlock;
     :: true ->  /* -> scRefund */
        Process_SmartContract_state = scRefund;
     fi;
  :: (Process_SmartContract_state == scUnlock) ->
     ch_MF_bi ! 1;  /* send message */
     Process_SmartContract_state = scLast;
  :: (Process_SmartContract_state == scLast) ->
     if
     :: (milestone_i >= MAX_MILESTONES) ->  /* exit loop */
        Process_SmartContract_state = scEndOk;
     :: (milestone_i < MAX_MILESTONES) ->  /* loop back */
        milestone_i++;
        Process_SmartContract_state = scVoting;
     fi;
  :: (Process_SmartContract_state == scEndOk) ->
     Process_SmartContract_state = DONE;
     break;
  :: (Process_SmartContract_state == scRefund) ->
     Process_SmartContract_state = scEndFail;
  :: (Process_SmartContract_state == scEndFail) ->
     Process_SmartContract_state = DONE;
     break;
  od;
  Process_SmartContract_state = DONE;
}

/* --- Process_Investor --- */
active proctype Process_Investor() {
  byte milestone_i = 0;

  do
  :: (Process_Investor_state == iStart) ->
     Process_Investor_state = iKYC;
  :: (Process_Investor_state == iKYC) ->
     Process_Investor_state = iInvest;
  :: (Process_Investor_state == iInvest) ->
     ch_MF_invest ! 1;  /* send message */
     Process_Investor_state = iVote;
  :: (Process_Investor_state == iVote) ->
     ch_MF_vote ! 1;  /* send message */
     Process_Investor_state = iEnd;
  :: (Process_Investor_state == iEnd) ->
     Process_Investor_state = DONE;
     break;
  od;
  Process_Investor_state = DONE;
}

/* LTL Properties */
ltl terminates_Process_Author { <>(Process_Author_state == DONE) }
ltl terminates_Process_Platform { <>(Process_Platform_state == DONE) }
ltl terminates_Process_SmartContract { <>(Process_SmartContract_state == DONE) }
ltl terminates_Process_Investor { <>(Process_Investor_state == DONE) }

/* Deadlock freedom is checked by SPIN's built-in invalid-end-state detection */
